### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by ternyavsky** [spywhere/tmux-now-playing#9]
`
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#latest'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'spywhere/tmux-now-playing'

set-option -g status-position top

set -g @catppuccin_status_modules_right "user cpu #{now_playing}"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

`
![image](https://github.com/user-attachments/assets/365e1508-968c-4f44-9bc5-89d4cd466958)

**Comment by spywhere** [comment]
I don't think this was related to tmux-now-playing itself. This is most likely caused by your catppuccin plugin.

`#{now_playing}` supposed to set in tmux's `status-left` or `status-right` option, but this line

```
set -g @catppuccin_status_modules_right "user cpu #{now_playing}"
```

doesn't seem to be about tmux's option. You might need to take a look on how catppuccin module works and try integrated this plugin into it instead.
